content_extraction:
  max_retries: 5
  parallel_workers: 5
crawling:
  max_depth: 3
  max_urls_per_site: 100
output:
  content_dir: extracted_content
  final_data: company_data.json
  logs_dir: logs
  progress_dir: progress
  urls_dir: .
url_labeling:
  batch_size: 50
  enabled: true
value_extraction:
  model: gpt-4o-mini
  temperature: 0.2
